version: "3.9"

services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: todaii_english
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./todaii_dump.sql:/docker-entrypoint-initdb.d/todaii_dump.sql

  admin-api:
    build:
      context: ./apps/admin-api/
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todaii_english?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
    ports:
      - "8082:8082"

  user-api:
    build:
      context: ./apps/user-api/
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todaii_english?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
    ports:
      - "8081:8081"

volumes:
  mysql_data:
